package com.breakdark.certificados_parroquia_vc.view;

import java.util.List;
import com.breakdark.certificados_parroquia_vc.model.Bautismo.*;
import javax.swing.table.DefaultTableModel;
import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;
import javax.swing.UIManager;

/**
 * Ventana principal para la aplicacion
 *
 * @author BreakDark
 * @version 1.0
 */
public class Principal extends javax.swing.JFrame {

    private final BautismoService bautismoService;
    private List<Bautismo> bautismos;

    /**
     * Creando el nuevo formulario Principal
     */
    public Principal() {
        ApplicationContext context = new ClassPathXmlApplicationContext("spring-config_development.xml");   // development
        //ApplicationContext context = new ClassPathXmlApplicationContext("spring-config.xml");   // production
        bautismoService = (BautismoService) context.getBean("bautismoService");
        initComponents();
        buscarBautismos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPanelPrincipal = new javax.swing.JTabbedPane();
        jPanelBautismo = new javax.swing.JPanel();
        jScrollPaneBautismo = new javax.swing.JScrollPane();
        jTableBautismo = new javax.swing.JTable();
        jPanelPrimeraComunion = new javax.swing.JPanel();
        jPanelConfirmacion = new javax.swing.JPanel();
        jPanelMatrimonio = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Certificados Parroquia Villa Copacabana");
        jScrollPaneBautismo.setViewportView(jTableBautismo);
        if (jTableBautismo.getColumnModel().getColumnCount() > 0) {
            jTableBautismo.getColumnModel().getColumn(0).setResizable(false);
            jTableBautismo.getColumnModel().getColumn(1).setResizable(false);
            jTableBautismo.getColumnModel().getColumn(2).setResizable(false);
            jTableBautismo.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout gl_jPanelBautismo = new javax.swing.GroupLayout(jPanelBautismo);
        jPanelBautismo.setLayout(gl_jPanelBautismo);
        gl_jPanelBautismo.setHorizontalGroup(
            gl_jPanelBautismo.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gl_jPanelBautismo.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneBautismo)
                .addContainerGap())
        );
        gl_jPanelBautismo.setVerticalGroup(
            gl_jPanelBautismo.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gl_jPanelBautismo.createSequentialGroup()
                .addComponent(jScrollPaneBautismo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPanelPrincipal.addTab("Bautismo", jPanelBautismo);

        javax.swing.GroupLayout gl_jPanelPrimeraComunion = new javax.swing.GroupLayout(jPanelPrimeraComunion);
        jPanelPrimeraComunion.setLayout(gl_jPanelPrimeraComunion);
        gl_jPanelPrimeraComunion.setHorizontalGroup(
            gl_jPanelPrimeraComunion.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 655, Short.MAX_VALUE)
        );
        gl_jPanelPrimeraComunion.setVerticalGroup(
            gl_jPanelPrimeraComunion.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 491, Short.MAX_VALUE)
        );

        jTabbedPanelPrincipal.addTab("Primera Comunión", jPanelPrimeraComunion);

        javax.swing.GroupLayout gl_jPanelConfirmacion = new javax.swing.GroupLayout(jPanelConfirmacion);
        jPanelConfirmacion.setLayout(gl_jPanelConfirmacion);
        gl_jPanelConfirmacion.setHorizontalGroup(
            gl_jPanelConfirmacion.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 655, Short.MAX_VALUE)
        );
        gl_jPanelConfirmacion.setVerticalGroup(
            gl_jPanelConfirmacion.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 491, Short.MAX_VALUE)
        );

        jTabbedPanelPrincipal.addTab("Confirmación", jPanelConfirmacion);

        javax.swing.GroupLayout gl_jPanelMatrimonio = new javax.swing.GroupLayout(jPanelMatrimonio);
        jPanelMatrimonio.setLayout(gl_jPanelMatrimonio);
        gl_jPanelMatrimonio.setHorizontalGroup(
            gl_jPanelMatrimonio.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 655, Short.MAX_VALUE)
        );
        gl_jPanelMatrimonio.setVerticalGroup(
            gl_jPanelMatrimonio.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 491, Short.MAX_VALUE)
        );

        jTabbedPanelPrincipal.addTab("Matrimonio", jPanelMatrimonio);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPanelPrincipal)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanelBautismo;
    private javax.swing.JPanel jPanelPrimeraComunion;
    private javax.swing.JPanel jPanelConfirmacion;
    private javax.swing.JPanel jPanelMatrimonio;
    private javax.swing.JScrollPane jScrollPaneBautismo;
    private javax.swing.JTabbedPane jTabbedPanelPrincipal;
    private javax.swing.JTable jTableBautismo;
    // End of variables declaration//GEN-END:variables

    /**
     * metodo que busca los bautismos
     */
    private void buscarBautismos() {
        bautismos = bautismoService.obtenerTodosLosBautismos();
        String[] columnas = {"id", "nombre completo", "fecha de bautismo", "fecha de nacimiento"};
        DefaultTableModel tableModelBautismo = new DefaultTableModel(columnas, 0);
        jTableBautismo.setModel(tableModelBautismo);
        // cargamos la tabla
        for (Bautismo bautismo : bautismos) {
            Object[] dataBautismo = {bautismo.getId(), bautismo.getNombres(), bautismo.getFecha_bautismo(), bautismo.getFecha_nacimiento()};
            tableModelBautismo.addRow(dataBautismo);
            //System.out.println(bautismo);
        }
    }
}
